http:
  commit_url: "http://app:8080/commit"
  port: 9090

rabbit_mq:
  host:       "broker"
  port:       5672
  queue_name: "tasks"

postgres:
  host:            "db"
  port:            5432
  user:            "postgres"
  password:        "postgres"
  dbname:          "app_db"
  sslmode:         "disable"

prometheus:
  port: 9090

grafana:
  port: 3000
  admin_password: "admin123"
