http:
  address: ":8080"

rabbit_mq:
  host:       "broker"
  port:       5672
  queue_name: "tasks"

postgres:
  host:            "db"
  port:            5432
  user:            "postgres"
  password:        "postgres"
  dbname:          "app_db"
  sslmode:         "disable"

redis:
  host: "redis"
  port: 6379
  password: "redis"
  db: 0

migrations_enabled: true